#!/bin/sh
# Create local DB if it doesn't already exist
set -e

if [ -z "$1" ]; then
  echo 'usage: db/boot name'
  exit 2
fi

createdb "$1" > /dev/null 2>&1 || echo "Skipping, database $1 already exists"
